language: r
sudo: required
cache: packages

os:
  - osx

addons:
  postgresql: 9.6

r_packages:
  - devtools

r_github_packages:
  - chris-prener/stlData
  - tidyverse/ggplot2

script:
  - R -e "rmarkdown::render('tests/test.Rmd')"
  - R -e "rmarkdown::render('tests/testMap.Rmd')"
  
after_success:
  - dropdb postgis
  - createdb postgis
  - psql -d postgis -c "CREATE EXTENSION postgis;"
  - psql -d postgis -c "GRANT CREATE ON DATABASE postgis TO travis"