language: r
sudo: false
cache: false

os:
  - osx

# r_packages:
#  - devtools

r_github_packages:
  - chris-prener/stlData
  - tidyverse/ggplot2

script:
  - R -e "rmarkdown::render('tests/test.Rmd')"
  - R -e "rmarkdown::render('tests/testMap.Rmd')"
 