language: r
sudo: required
cache: packages

addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.3

r_packages:
  - devtools

r_github_packages:
  - chris-prener/stlData
  - tidyverse/ggplot2

before_install:
    - chmod +x ./.travis/install.sh
    - ./.travis/install.sh

script:
  - R -e "rmarkdown::render('tests/test.Rmd')"
  - R -e "rmarkdown::render('tests/testMap.Rmd')"
  
after_success:
  - dropdb postgis
  - createdb postgis
  - psql -d postgis -c "CREATE EXTENSION postgis;"
  - psql -d postgis -c "GRANT CREATE ON DATABASE postgis TO travis"